//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class advertisertb
    {
        public int advertiserID { get; set; }
        public string ad_name { get; set; }
        public string ad_content { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<sbyte> status { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<sbyte> payment_status { get; set; }
        public string username { get; set; }
        public Nullable<decimal> balance { get; set; }
    }
}
