//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gpdbEntities : DbContext
    {
        public gpdbEntities()
            : base("name=gpdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<videotb> videotb { get; set; }
        public virtual DbSet<comtb> comtb { get; set; }
        public virtual DbSet<usertb> usertb { get; set; }
        public virtual DbSet<advertisertb> advertisertb { get; set; }
        public virtual DbSet<transaction_recordtb> transaction_recordtb { get; set; }
    }
}
