//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction_recordtb
    {
        public int transactionID { get; set; }
        public string ad_name { get; set; }
        public string transaction_type { get; set; }
        public decimal amount { get; set; }
        public System.DateTime transaction_date { get; set; }
        public string alipay_trade_no { get; set; }
        public string trade_status { get; set; }
        public string username { get; set; }
    }
}
