//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class videotb
    {
        public int videoID { get; set; }
        public string title { get; set; }
        public string link { get; set; }
        public string cover { get; set; }
        public string tag { get; set; }
        public string year { get; set; }
        public Nullable<float> rating { get; set; }
        public string status { get; set; }
        public Nullable<int> hotscore { get; set; }
        public string type { get; set; }
        public string tvid { get; set; }
        public string desc { get; set; }
        public string date { get; set; }
        public Nullable<int> time { get; set; }
        public string bigcover { get; set; }
        public string director { get; set; }
        public string actor { get; set; }
    }
}
